units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
  $default_width: cx 
  $default_height: cy

points:
  zones:
    matrix:
      anchor:
        shift: [100, -150]
      columns:
        outer:
          rows.mod.skip: true 
          key:
            splay: 4
        pinky:
          rows.mod.skip: true
          key:
            splay: 0
        ring:
          rows.mod.skip: true
          key:
            splay: -4
            stagger: 5 
        middle:
          key.stagger: 2.5
        index:
          key.stagger: -2.5
        inner:
          rows.mod.skip: true
          key.stagger: -2.5
      rows:
        mod:
        bottom:
        home:
        top:
        num:


    thumbs:
      anchor:
        ref: matrix_inner_mod
        shift: [2,-2]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        layer:
          key.splay: -15 
        space:
          key:
            splay: -15
            shift: [2,-2]
      rows:
        cluster:

outlines:
  raw: 
    - what: rectangle
      where: true
      bound: true 
      size: [px,py]
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_bottom
          shift: [-0.5px,-0.5py]
        - ref: matrix_middle_mod
          shift: [-0.5px,-0.5py]
        - ref: matrix_middle_mod
          shift: [0.3px,-0.5py]
        - ref: matrix_index_mod
          shift: [-0.4px,-0.5py]
        - ref: matrix_index_mod
          shift: [0.3px,-0.5py]
        - ref: thumbs_layer_cluster
          shift: [-0.4px,-0.5py]
        - ref: thumbs_space_cluster
          shift: [0.5px,-0.5py]
        - ref: thumbs_space_cluster
          shift: [0.5px,0.5py]
        - ref: matrix_inner_num
          shift: [1.6px,0.5py]
        - ref: matrix_inner_num
          shift: [0.5px,0.5py]
        - ref: matrix_index_num
          shift: [0.5px,0.5px]
        - ref: matrix_index_num
          shift: [-0.3px,0.5py]
        - ref: matrix_middle_num
          shift: [0.4px,0.5py]
        - ref: matrix_middle_num
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_num
          shift: [-0.5px,0.5py]
        - ref: matrix_outer_num
          shift: [0.5px,0.5py]
        - ref: matrix_outer_num
          shift: [-0.5px,0.5py]

  combo:
    - name: board
    - operation: subtract
      name: keys

pcbs:
  tutorial:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref.aggregate.parts: [matrix_inner_top]
          shift: [1px,0.25px]
          rotate: -90
